sudo: false

language: node_js

node_js:
  - node

env:
 global:
    - export NODE_ENV=test
    - export COVERALLS_REPO_TOKEN=WTDboADDnl7CQvMBubibPVCvxkfkGGxOi

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g standard

before_script:


script:
  - npm run test:cover